### ISSUE TITLE
feature request: introdurre nella scheda dello sticker il testo che la caratterizza

### ISSUE THREAD

**Issue by aborruso** [archeostickers/archeostickers.github.io#1]
Cari archeostickers people,
avevo bisogno di trovare la scheda dello sticker con scritto "MMMMM", perché un mio è un grande fan della stessa. Allora mi sono lanciato in una classica ricerca ["site:www.archeostickers.com Patrizio Romano"](https://www.google.it/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:www.archeostickers.com+MMMMM), che però non ha prodotto risultato.

Mentre "[site:www.archeostickers.com Patrizio Romano](https://www.google.it/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site%3Awww.archeostickers.com+Patrizio+Romano)" works like a charm.

Se inserito il testo nella scheda, sarà più facile cercare cose come "Maria, io esco", "ciaone", ecc..

Sotto un esempio.

Vi stimo

![2016-03-17_15h11_53](https://cloud.githubusercontent.com/assets/30607/13848558/b3ab0ffc-ec52-11e5-837f-9dc5fc472ebc.png)

**Comment by lucacorsato** [comment]
ACCOLTA!
